### ISSUE TITLE
host ?domain?

### ISSUE THREAD

**Issue by p3im4n** [h-mdm/apuppet-server#1]
hi Mr @h-mdm 
I need more info abut host and domain issue
you mentioned a valid  domain should exist
how about the host?
where should be  "apuppet-server" located on compile time?
on my pc?
or in the host which be linked to domain right now ?
how could i upload "apuppet-server" on a host?
what about static ip ? domain ip?   "apuppet-server" ip?

sorry for my bad English

best regard

**Comment by h-mdm** [comment]
aPuppet uses HTTPS so it requires a domain which must belong to you. IP address cannot be used with HTTPS, because you cannot get a HTTPS certificate for an IP address.

To deploy aPuppet server on a host, just copy the contents of the "remote-control" directory to the host and run the install.sh script. An alternative way would be to clone the project from github to your host.

**Comment by p3im4n** [comment]
> just copy the contents of the "remote-control" directory to the host and run the install.sh script.

there is no "remote-control" directory!!!!!
do you mean after install.sh script?

> An alternative way would be to clone the project from github to your host.

so,doesn't I need install.sh anymore?

**Comment by h-mdm** [comment]
Sorry, I meant the project root directory, it is "apuppet-server". The README.md file has been updated as appropriate.

You need to run install.sh after cloning or copying the project, because this is the deployment script. The script uses Ansible to configure the service and Docker Compose to run it. Without running this script, aPuppet server will not work.
