### ISSUE TITLE
deployment server

### ISSUE THREAD

**Issue by zaheerkzz** [h-mdm/apuppet-server#11]
can we deploy apuppet-server locally on locallhost or running any local server on ubuntu. any help will be appriciated.
thank you

**Comment by h-mdm** [comment]
Do you mean deploying aPuppet server in a LAN? 

APuppet requires a valid HTTPS certificate. You can deploy it in a LAN, but you still need to use a domain available on the Internet (to get a certificate). Once you get a certificate, you can assign your domain to a local IP by using your local DNS, and aPuppet will work in LAN. For LAN-based installations, I recommend to purchase a commercial certificate like Comodo PositiveSSL because it is valid for a long time.

See more details here: https://apuppet.org/remote-control-in-lan/

**Comment by zaheerkzz** [comment]
thank you so much for your quick response.
